### ISSUE TITLE
vNext

### ISSUE THREAD

**Issue by andywilsonuk** [andywilsonuk/StringTokenFormatter#24]
@TonyValenti I've been spending some time reworking the library and whilst I'm not yet ready to commit, I wanted to give you a heads up that it's on its way.

It'll support async of course but I've also been rethinking how the flow works and simplifying the structure.  I'll keep you posted.

**Comment by TonyValenti** [comment]
Hi @andywilsonuk -
I'm interested in seeing what you do!
Regarding Async support, I played around with that a lot and I actually think it is not a good idea.  The reason is because async typically implies "something that could take a while" (ie, a web request) and string interpolation typically implies "something that should be near instant".  Because of that those two things, you get into lots of weird issues trying to make things perform and operate as expected (for example, caching tasks/valuetasks).

For async usage, I found that a better approach was to scan the interpolated string for the tokens, then asyncly build my TokenValueContainer.  Once I had that, then I'd just FormatToken as normal.

**Comment by andywilsonuk** [comment]
That is a very good point. I've been trying to shoehorn in async behaviour but it doesn't fit right: containers, converters and FormatToken, all should have both async and sync methods and that'll end up with a lot of code that's only used by one path or the other.

Determining the tokens, pulling in the values (async) and then populating the container gets my vote.

I'll keep going on the other fronts but look to remove the async parts that I've added.

**Comment by andywilsonuk** [comment]
@TonyValenti I think I'm pretty happy with where the vNext is at; I've committed the changes to the branch: https://github.com/andywilsonuk/StringTokenFormatter/tree/vNext/StringTokenFormatter

I haven't updated the tests nor the readme but I'd like to get your feedback before wrapping it up.

**Comment by TonyValenti** [comment]
Hi @andywilsonuk -
I'm on a cruise this week so I haven't been able to fully review, however, I've given things a cursory glance and there are a few things that stood out to me:
1.  There seemed to be some uses of "lazy" in the constructors. Id definitely recommend reviewing this to make sure it is actually faster. Lazy often incurs locking which can be slower than just doing the work for small operations. I had actually considered making the regexes use source gen so they are all precompiled and ultra fast. 

2.  I noticed a few methods that returned hash sets. I'm reviewing on my phone so it is hard for me to fully gleam the context, but it seems like the methods might be around getting the used Tokens from a string. It seems like the methods/properties would always return a new hash set. I don't like Hash sets because they are mutable. I would suggest making them an ILookup and either making it a cached property on the interpolated string or an extension method that generates the ILookup.  I think I like the extension method better because it doesn't incur the computation tax on each invocation and it is more clear that it generates a new one. 

I'll try to review things in more detail when I get back next week.

**Comment by andywilsonuk** [comment]
Great stuff, yeah have a better look when you can, enjoy your holiday!

I should have talked about the parts, `StringTokenFormatterSettings` should give you a good idea of what's available configuration-wise and `InterpolatedStringResolver` (not sure about the name) I see as the preferred way to resolve the tokens in a `string` using an `ITokenValueContainer`. The string extensions are still there however I'm unconvinced that they represent the 'best' was to use the library anymore owing to how the complexity has increased over time.

The `InterpolatedStringParser` splits the string into token and literal segments to produce the `InterpolatedString`.

The `InterpolatedStringExpander` is where the `InterpolatedString` is evaluated, mapping token values including any conversion and formatting.

**Comment by TonyValenti** [comment]
Can you merge this and then I'll review and make any changes?

**Comment by TonyValenti** [comment]
@andywilsonuk ?

**Comment by andywilsonuk** [comment]
Ok, now merged @TonyValenti. Assuming that the code itself is sound (which it probably isn't), the tests need updating/rewriting and we probably need some deprecated methods to support existing clients whilst they transition over to the new functionality.

You previously mentioned use of Lazy so it'll comment specifically that one of the goals I was trying to achieve was to improve app startup time. I haven't any evidence that using the Lazy actually does that in this instance however.

**Comment by TonyValenti** [comment]
Hey @andywilsonuk - Can you zoom with me?
I'm able to review things better and I have some questions about your approach.

Can we jump on a Zoom?  I'd rather talk through things.
If you're available now-ish:
[Zoom Now](https://us02web.zoom.us/j/4025099270)

Otherwise:
[General Meeting](https://calendly.com/tv--15/general_meeting)

Also, I'm seeing things that will actually hurt performance quite a bit.  As an example, this code:
```
public static TokenSyntax Curly => new("{", "}", "{{");
```
will actually create a new object every time the property is accessed.  Because records are being used, this isnt so obvious because ```==``` is overridden.  Check it out with this:
```
namespace ConsoleApp21 {
    internal class Program {
        static void Main(string[] args) {
            var C = Foo;
            var D = Foo;

            var OE = C == D;
            var RE = object.ReferenceEquals(C, D);

            Console.WriteLine($@"Object Equals:    {OE}");
            Console.WriteLine($@"Reference Equals: {RE}");

        }

        public static TestRecord Foo => new();

    }

    public record TestRecord { 
    
    }
}
```

Anyway, I'd love to talk through things.

**Comment by andywilsonuk** [comment]
Unfortunately I've limited internet for the next two weeks. The code is very rough at the moment because I spent most of the time playing with the structure but now is the time for a critical eye over whether the design is obvious and performance is good.

That Curly example you've pointed out should be a singleton instance, seems like I need to go over the code again.

**Comment by TonyValenti** [comment]
Let's zoom when you get back.  I like some of the concepts you have and want to talk through it.  But I think that some of the perf enhancements you had in mind will actually have the opposite effect. 

Alternatively, would you prefer I just revert and then run with it?

**Comment by andywilsonuk** [comment]
v7 released as major version with breaking changes.
