### ISSUE TITLE
Support for multiline replacements

### ISSUE THREAD

**Issue by prochnowc** [andywilsonuk/StringTokenFormatter#8]
Nice library .. but i cant use it because i need to replace tokens for a whole text file.
In the code i saw the `Regex` is initialized using Singleline option.
Please consider adding support for multiline.

Also, replacement doesnt seem to work at all when i use start tokens which have more than one character.

```
private class PropertyTokenMarkers : TokenMarkers
        {
            public string StartToken => "$(";
            public string EndToken => ")";
            public string StartTokenEscaped => "$$(";
            public string EndTokenEscaped => ")";
            public IEqualityComparer<string> TokenNameComparer => StringComparer.CurrentCultureIgnoreCase;
        }
```

Thanks!

**Comment by andywilsonuk** [comment]
Hi,

Hmm, I thought both those things were supported. I'll add some tests and get back to you.

Andy

**Comment by andywilsonuk** [comment]
Right, the token matching issue was because the EndToken and the EndTokenEscaped are the same character; I'm going to put in a fix for that.

I'm unable to replicate the issue with the text file; I tried a pattern like this which should be the same as parsing a whole file as a single string:

`string pattern = "first {two}" + Environment.NewLine + "third {two}";`

**Comment by prochnowc** [comment]
Ok - then i did not get any replacements because of the EndToken issue .. thanks for fixing!

**Comment by andywilsonuk** [comment]
2.0.7 should have this sorted for you.
